### ISSUE TITLE
Replace h2 titles to interactive tags

### ISSUE THREAD

**Issue by ilyanew** [garnich/webstorage#2]
Looks like it's "Accordion" component. So, more proper way to wrap titles (LocalStorage, SessionStorage, Cookies, IndexedDB) to <a> or <button>. And handle click on these interactive tags, not handle all Document.

https://github.com/garnich/webstorage/blob/7c3bcb829f336e97582a94307393d9c8599c9e8b/index.html#L75

**Comment by garnich** [comment]
https://github.com/garnich/webstorage/commit/6a50f12fe89e7f8e8d09e96f4be3356e09b52d37

**Comment by garnich** [comment]
https://github.com/garnich/webstorage/commit/c5694165c538a1d47c0640772627209fda018614
https://github.com/garnich/webstorage/commit/ea15f08e22c9ca1d92ad8c59981b86df5b62b20d
https://github.com/garnich/webstorage/commit/8ecc5d154aa926f5a60a1e563bc383fff0bd7a09
